### ISSUE TITLE
control horizontal swipe

### ISSUE THREAD

**Issue by JFreyberger** [juliome10/DoubleViewPager#6]
Hi,

thank you very much for your good work. It saved me a lot of time. Now I'd like to do a slight modification: I'd like to forbid horizontal scrolling for certain positions. For example if you are currently showing a view of the first column a horizontal swipe to the second column should only be possible if you have opened the first view of the first column, but if you're actually showing some other view of the first column and try to do a vertical swipe I'd like to avoid scrolling and show the EdgeEffectCompat things. Do you have a tip for me, where it could be the best place to add some kind of callback giving the current column and row and return a bool for indicationg whether a swipe is allowed? Btw. do you know whether this EdgeEffectCompat can also be used at bottom and top when reaching the end of a column?

Thanks and best regards,
Johannes

**Comment by JFreyberger** [comment]
... solved :-) ...

**Comment by IlanVokov** [comment]
can you show your solution?

**Comment by JFreyberger** [comment]
sorry, I don't have this code anymore. I decided to use a different approach as this way seemed to become more and more hacky.
